export const CHANGE_NAV_SELECTED = 'CHANGE_NAV_SELECTED';
export const LOG_IN_TO_SIGN_UP = 'LOG_IN_TO_SIGN_UP';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_INFO_ADDED = 'USER_INFO_ADDED';